### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by AHOHNMYC**
* Updated actions to use node20
* Updated vcpkg slice to capture new libgit2 1.8.0 with fetch depth options
* Added `setup-msbuild` action as msbuild doesn't exist on runner out of the box

### CODE REVIEW

**Comment by ShadowMonster99** [comment]
What's the reasoning behind truncating the version in `./version`

**Comment by AHOHNMYC** [comment]
There is no reason. I guess, its because of broken autoversion in cloned repo. I'll restore status quo when PR will be ready to merge

**Comment by ShadowMonster99** [comment]
I've made a [new commit](https://github.com/SteamClientHomebrew/Millennium/commit/6feced638ce16a4ceccf9cc5ac478355b54ee480) where explicitly specify the version of libgit2 without updating the vcpkg baseline, to prevent side effects.

**Comment by AHOHNMYC** [comment]
Yeah, I got it when saw `Resolve conflicts` 😄 Nice job. I'll revert all about libgit2 and stuff

What about other changes? In my cloned repo I haven't success untill I've added `setup-msbuild`. My guess is GitHub Action caches in your repo.

**Comment by ShadowMonster99** [comment]
Yeah, you're totally right. I must have changed something removing the setup of MS build, but I didn't matter at the time because it was already cached. Good thing you caught it.

**Comment by ShadowMonster99** [comment]
Just revert the changes made to `vcpkg-configuration.json` and `version` and it should be good to merge. Also, just checking, your proposed changes to vcpkg is just a submodule update correct? GitHub doesn't provide much information.

**Review by ShadowMonster99 — APPROVED** [review]

**Comment by ShadowMonster99** [comment]
Something seems to have messed up in one of these commits. It seems libgit2 isn't being statically linked and its requiring zlib1.dll. It builds correctly locally, but not from the CI

**Comment by ShadowMonster99** [comment]
Not entirely sure what caused it, but it seems one of our recent commits messed up Millennium. Its been fixed but I've reverted your changes.

**Comment by AHOHNMYC** [comment]
Oh, okay. Sadly it's expected. I'm thinking about little exe loader with bunch of self tests...

**Comment by ShadowMonster99** [comment]
Oops, missed your message, GitHub decided it wasn't going to notify me. That's a great idea and its been something I've wanted to do however I just didnt have time to focus on it.

**Pull request merged**
